### ISSUE TITLE
Opam error

### ISSUE THREAD

**Issue by emiquey** [uds-psl/autosubst-ocaml#14]
Hi,

While trying to install autosubst-ocaml with opam, I get a strange error about a dependency to Coq<8.14.0  : 
```
$ opam install coq-autosubst-ocaml
[ERROR] Package conflict!
  * Missing dependency:
    - coq < 8.14
    not available because the package is pinned to version 8.19.0

No solution found, exiting
```
I don't have any idea on how the opam dependencies work and are generated, but I guess that this is rather an issue with the opam package than with my opam installation, right? Any idea on how to fix it?
Cheers,

Étienne

**Comment by yforster** [comment]
Sorry for being late here. The new packages are merged in the opam repository now, so the error should be gone. Would you mind testing again?

**Comment by emiquey** [comment]
Seems okay now !
